server:
  port: 8085
  max-http-header-size: 64KB
spring:
  application:
    name: cf-sms-api
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: ${cf.env.dubbo.registry-address}
