server:
  port: 8086
  max-http-header-size: 64KB
spring:
  application:
    name: cf-chat-api
  profiles:
    active: dev
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
auth:
  tokenValiditySeconds: ${AUTH_TOKEN_VALIDITY_SECONDS:1200}
  clientId: ${AUTH_CLIENT_ID:oauth2_client_id}
  clientSecret: ${AUTH_CLIENT_SECRET:oauth2_client_secret}
  cookieDomain: ${AUTH_COOKIE_DOMAIN:xuecheng.com}
  cookieMaxAge: ${AUTH_COOKIE_MAX_AGE:-1}
