server:
  port: 8097
  max-http-header-size: 64KB
spring:
  application:
    name: cf-pay-admin
  profiles:
    active: dev,common
auth:
  tokenValiditySeconds: 1200
  clientId: oauth2用户名，记得在对应的数据库配置用户名
  clientSecret: oauth2密码，记得在对应数据库配置密码
  cookieDomain: xuecheng.com
  cookieMaxAge: -1

