server:
  port: 8070
  servlet:
    context-path: /
spring:
  application:
    name: cf-dh
dh:
  forward:
    coding: GBK
    ledBrand: yang_bang
    cameraInfoes:
      - ip: ${DH_CAMERA_IP:192.168.3.200}
        server: ${DH_CAMERA_SERVER:http://192.168.3.19:8089}
        port: ${DH_CAMERA_PORT:37777}
        username: ${DH_CAMERA_USERNAME:admin}
        password: ${DH_CAMERA_PASSWORD:admin123}
        uuid: ${DH_CAMERA_UUID:6F01FFAPAJ65519}
    ledConfigs:
      - ip: ${DH_LED_IP:192.168.3.250}
        port: ${DH_LED_PORT:5005}
        uuid: ${DH_LED_UUID:6F01FFAPAJ65519}
