server:
  port: ${cf.env.forward.dh.server-port}
  servlet:
    context-path: /
spring:
  application:
    name: cf-dh
dh:
  forward:
    coding: ${cf.env.forward.dh.coding}
    ledBrand: ${cf.env.forward.dh.led-brand}
    cameraInfoes:
      - ip: ${cf.env.forward.dh.camera-primary.ip}
        server: ${cf.env.forward.dh.camera-primary.server}
        port: ${cf.env.forward.dh.camera-primary.port}
        username: ${cf.env.forward.dh.camera-primary.username}
        password: ${cf.env.forward.dh.camera-primary.password}
        uuid: ${cf.env.forward.dh.camera-primary.uuid}
    ledConfigs:
      - ip: ${cf.env.forward.dh.led-primary.ip}
        port: ${cf.env.forward.dh.led-primary.port}
        uuid: ${cf.env.forward.dh.led-primary.uuid}
