spring:
  datasource:
    name: ${cf.env.mysql.database}
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${cf.env.mysql.url}
    username: ${cf.env.mysql.username}
    password: ${cf.env.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32
mybatis:
  mapperLocations: classpath:com.cf.ucenter.dao.mapper/*.xml
  configLocation: classpath:config/SqlMapConfig.xml
