server:
  port: 8083
spring:
  application:
    name: cf-chat-service
  datasource:
    name: ${cf.env.mysql.database}
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${cf.env.mysql.url}
    username: ${cf.env.mysql.username}
    password: ${cf.env.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32
  data:
    mongodb:
      uri: ${cf.env.mongodb.uri}
      database: ${cf.env.mongodb.database}
  redis:
    host: ${cf.env.redis.host}
    port: ${cf.env.redis.port}
    password: ${cf.env.redis.password}
    database: ${cf.env.redis.database}
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1
mybatis:
  mapperLocations: classpath:com.cf.chat.dao.mapper/*.xml
  configLocation: classpath:config/SqlMapConfig.xml
dubbo:
  scan:
    base-packages: com.cf.chat.service.impl
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20883
    threads: 200
    accepts: 0
  registry:
    address: ${cf.env.dubbo.registry-address}
  provider.filter: -exception
