server:
  port: 8082
  servlet:
    context-path: /auth
spring:
  application:
    name: cf-ucenter-auth
  profiles:
    active: dev,common
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
auth:
  tokenValiditySeconds: 1200
  clientId: oauth2用户名，记得在对应的数据库配置用户名
  clientSecret: oauth2密码，记得在对应数据库配置密码
  cookieDomain: xuecheng.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng

dubbo:
  scan:
    base-packages: com.cf.ucenter.auth.service
  protocol:
    port: 20882





