server:
  port: 8092
  max-http-header-size: 64KB
spring:
  application:
    name: cf-carpark-admin
  profiles:
    active: dev
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:caifeng}?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${MYSQL_USER:caifeng}
    password: ${MYSQL_PASSWORD:caifeng}
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /home/app/tomcat_upload_temp
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
auth:
  tokenValiditySeconds: ${AUTH_TOKEN_VALIDITY_SECONDS:1200}
  clientId: ${AUTH_CLIENT_ID:oauth2_client_id}
  clientSecret: ${AUTH_CLIENT_SECRET:oauth2_client_secret}
  cookieDomain: ${AUTH_COOKIE_DOMAIN:xuecheng.com}
  cookieMaxAge: ${AUTH_COOKIE_MAX_AGE:-1}