server:
  port: ${cf.env.forward.hk.server-port}
  servlet:
    context-path: /
spring:
  application:
    name: cf-hk
hk:
  forward:
    baseUrl: ${cf.env.forward.hk.base-url}
    localIP: ${cf.env.forward.hk.local-ip}
    deviceIP: ${cf.env.forward.hk.device-ip}
    port: ${cf.env.forward.hk.port}
    username: ${cf.env.forward.hk.username}
    password: ${cf.env.forward.hk.password}
