server:
  port: ${random.int[1024,9999]}
  servlet:
    context-path: /
spring:
  application:
    name: cf-hk
hk:
  forward:
    baseUrl: http://${HK_BASE_HOST:192.168.3.19}
    localIP: ${HK_LOCAL_IP:192.168.3.252}
#    deviceIP: 192.168.10.61,192.168.10.62,192.168.10.63,192.168.10.64
    deviceIP: ${HK_DEVICE_IP:192.168.3.249}
    port: ${HK_PORT:8000}
    username: ${HK_USERNAME:admin}
    password: ${HK_PASSWORD:abcde12345}